---
###############################################################################
# Forgejo Install
###############################################################################
# Install required base packages; download, verify and install specified
# Forgejo version from codeberg release.

- name: 'Install | packages'
  ansible.builtin.include_role:
    name: 'r_pufky.deb.apt'
  vars:
    apt_packages:
      - '{{ forgejo_role_packages }}'
      - '{{ forgejo_role_redis if _forgejo_srv_redis_enable.raw else [] }}'
    apt_package_update_cache: true

- name: 'Install | binary {{ _forgejo_srv_version.raw }}'
  when: not _forgejo_srv_force_config_only_enable.raw
  ansible.builtin.include_role:
    name: 'r_pufky.deb.repo'
  vars:
    repo_host: 'codeberg'
    repo_release_owner: '{{ forgejo_role_repo_release_owner }}'
    repo_release_repo: '{{ forgejo_role_repo_release_repo }}'
    repo_release_tag: '{{ _forgejo_srv_version.raw }}'
    repo_release_asset: '{{ forgejo_role_repo_release_asset }}'
    repo_release_checksum: '{{ forgejo_role_repo_release_asset }}.sha256'
    repo_release_signature: '{{ forgejo_role_repo_release_asset }}.asc'
    repo_release_specifier: '{{ forgejo_role_repo_release_specifier }}'
    repo_release_gpg_key_id: '{{ _forgejo_srv_gpg_key_id.raw }}'
    repo_file_owner: '{{ _forgejo_srv_user.raw }}'
    repo_file_group: '{{ _forgejo_srv_group.raw }}'
    repo_extract_dir: '{{ forgejo_role_repo_extract_dir }}'
    repo_extract_symlink: '{{ forgejo_role_repo_extract_symlink }}'
    repo_extract_delete_old_versions:
      '{{ _forgejo_srv_delete_old_versions_enable.raw }}'
    repo_force_overwrite: '{{ _forgejo_srv_force_overwrite.raw }}'
    repo_extract_mode: 'a-st,o-rwx'
    repo_extract_binary_mode: '0755'
    repo_extract_extra_opts: '--strip-components=1'
