---
- name: 'Force forgejo_srv_container_enable=true (deb_container_enable)'
  when: deb_container_enable | default(false)
  ansible.builtin.set_fact:
    forgejo_srv_container_enable: true

- name: 'Assert'
  ansible.builtin.include_tasks: 'assert.yml'
- name: 'Annotate'
  ansible.builtin.include_tasks: 'annotate.yml'
- name: 'Prep'
  ansible.builtin.include_tasks: 'prep.yml'

- name: 'Install'
  when: not _forgejo_srv_force_config_only_enable.raw
  ansible.builtin.include_tasks: 'install.yml'

- name: 'Config'
  ansible.builtin.include_tasks: 'config.yml'

- name: 'Local users'
  when: _forgejo_srv_local_users.raw | length > 0
  ansible.builtin.include_tasks: 'local_users.yml'

- name: 'Validate'
  ansible.builtin.include_tasks: 'validate.yml'
