---
###############################################################################
# Forgejo Prep
###############################################################################
# Prepare system for install by creating user/group for service, and
# enumerating existing SSH keys if used. Stop services if they exist.
#
# Generates:
#   _forgejo_existing_service: dict - Systemd result object from service stop.

- name: 'Prep | manage users'
  when: _forgejo_srv_create_user.raw
  ansible.builtin.include_role:
    name: 'r_pufky.deb.users'
    tasks_from: 'role_account_add.yml'
  vars:
    users_role_user: '{{ forgejo_role_user }}'
    users_role_group: '{{ forgejo_role_group }}'

- name: 'Prep | enumerate system user {{ _forgejo_srv_user.raw }}'
  ansible.builtin.user:
    name: '{{ _forgejo_srv_user.raw }}'
  check_mode: true
  changed_when: false
  register: _forgejo_srv_user_query

- name: 'Prep | parse system user UID/GID'
  ansible.builtin.set_fact:
    _forgejo_srv_user: '{{
        _forgejo_srv_user |
        combine({"parsed": _forgejo_srv_user_query.uid,
                 "role": _forgejo_srv_user_query.home})
      }}'
    _forgejo_srv_group: '{{
        _forgejo_srv_group |
        combine({"parsed": _forgejo_srv_user_query.group})
      }}'

- name: 'Prep | update trusted user home directory'
  ansible.builtin.set_fact:
    _forgejo_cfg_server_ssh_trusted_user_ca_keys_filename: '{{
        _forgejo_cfg_server_ssh_trusted_user_ca_keys_filename |
        combine({"parsed":
            _forgejo_srv_user.role ~ "/.ssh/ca_trust_chain_root.pem"
            if
            _forgejo_cfg_server_ssh_trusted_user_ca_keys_filename.raw |
              length > 0
            else
            ""
          })
      }}'

- name: 'Prep | enumerate server host keys'
  when: _forgejo_cfg_server_ssh_server_host_keys.raw | length > 0
  block:
    - name: 'Prep | enumerate server host keys | query'
      delegate_to: 'localhost'
      ansible.builtin.find:
        paths: '{{ _forgejo_cfg_server_ssh_server_host_keys.raw }}'
        excludes: ['*.pub']
        follow: true
        recurse: true
        file_type: 'file'
      register: _forgejo_source_ssh_keys

    - name: 'Prep | enumerated server host keys | normalize paths'
      ansible.builtin.set_fact:
        _forgejo_parsed_ssh_keys: '{{
            _forgejo_parsed_ssh_keys | default([]) +
            [item.path |
             replace(_forgejo_cfg_server_ssh_server_host_keys.raw, "")]
          }}'
      loop: '{{ _forgejo_source_ssh_keys.files }}'
      loop_control:
        label: '{{ item.path }}'

    - name: 'Prep | enumerated server host keys | merge keys'
      ansible.builtin.set_fact:
        _forgejo_cfg_server_ssh_server_host_keys: '{{
            _forgejo_cfg_server_ssh_server_host_keys |
            combine({"parsed":
              _forgejo_cfg_server_ssh_server_host_keys.parsed | default([]) +
              [_forgejo_cfg_server_ssh_server_host_keys.role ~ "/" ~ item]
            })
          }}'
      loop: '{{ _forgejo_parsed_ssh_keys | default([]) | sort }}'

- name: 'Config | stop services'
  ansible.builtin.systemd:
    name: '{{ item }}'
    state: 'stopped'
  failed_when: false
  register: _forgejo_existing_service
  loop:
    - 'forgejo.service'
