---
###############################################################################
#  Pre Execution Tasks
###############################################################################
# Only use data annotations in role after merging role, defaults, runtime data.
# Service may not exist if first install.
#
# Backup running configuration if enabled before applying changes.

- name: 'Prep | fact | record start time'
  ansible.builtin.set_fact:
    forgejo__srv: "{{ forgejo___release | r_pufky.data.v3(

        _start=now(utc=True, fmt='%Y-%m-%dT%H%M%S'),
        _token=forgejo_srv_token,
        _user=forgejo_srv_user,
        _group=forgejo_srv_group,
        _harden=forgejo_srv_harden,
      ) }}"
    forgejo__cfg: "{{ {} | r_pufky.data.v3(

        _version=forgejo_srv_version,
        _package='forgejo-' ~ forgejo_srv_version[1:] ~ '-linux-amd64.xz',
        _package_bin='forgejo-' ~ forgejo_srv_version[1:] ~ '-linux-amd64',
        _url_base=forgejo___repo_url ~ forgejo_srv_version ~ '/',
        _app_d=forgejo___app._src_d ~ '/' ~ forgejo_srv_version,

        _users=forgejo_cfg_users,
        _file=forgejo_cfg_file,
        _d=forgejo_cfg_d | regex_replace('\\/$', ''),
        _backup_opts=forgejo_cfg_backup_opts | join(' '),

        _work_path=forgejo___app._var_d,
      ) }}"

- name: 'Prep | fact | parse metadata'
  ansible.builtin.set_fact:
    forgejo__cfg: "{{ forgejo__cfg | r_pufky.data.v3(

        _package_sig=forgejo__cfg._package ~ '.asc',
        _package_sum=forgejo__cfg._package ~ '.sha256',
        _src_bin=forgejo__cfg._app_d ~ '/' ~ forgejo__cfg._package_bin,
      ) }}"

- name: 'Prep | assert | config enabled and source defined'
  when: forgejo_flg_config
  ansible.builtin.assert:
    quiet: true
    that:
      - forgejo__cfg._file | length > 0
    fail_msg: |

      ✘ Config source not set.
      Config source enabled but no config source defined.

      forgejo_flg_config: {{ forgejo_flg_config }}
      forgejo_cfg_file: {{ forgejo__cfg._file }}

# Stop service early to pre-check existing install for backup dump.
- name: 'Prep | systemd | stop forgejo.service'
  ansible.builtin.systemd:
    name: 'forgejo.service'
    state: 'stopped'
  failed_when: false

- name: '{{ "Prep | filesystem | check " ~ forgejo___app._app_ini }}'
  ansible.builtin.stat:
    path: '{{ forgejo___app._app_ini }}'
  register: forgejo__check

- name: 'Prep | backup'
  when: forgejo__check.stat.exists and forgejo_flg_backup
  ansible.builtin.include_tasks: 'backup.yml'

- name: '{{ "Prep | account | query user " ~ forgejo__srv._user }}'
  ansible.builtin.command: '{{ "id " ~ forgejo__srv._user }}'
  failed_when: false
  register: forgejo__cfg_check
  changed_when: forgejo__cfg_check.rc > 0

- name: '{{ "Prep | account | query group " ~ forgejo__srv._group }}'
  ansible.builtin.command: '{{ "groups " ~ forgejo__srv._group }}'
  failed_when: false
  register: forgejo__group_check
  changed_when: forgejo__group_check.rc > 0

- name: '{{ "Prep | account | create group " ~ forgejo__srv._group }}'
  when: forgejo__group_check.rc != 0
  ansible.builtin.group:
    gid: '{{ forgejo___group.gid }}'
    name: '{{ forgejo___group.name }}'
    state: 'present'

- name: '{{ "Prep | account | create user " ~ forgejo__srv._user }}'
  when: forgejo__cfg_check.rc != 0
  ansible.builtin.user:
    name: '{{ forgejo___user.name }}'
    group: '{{ forgejo___user.group }}'
    uid: '{{ forgejo___user.uid }}'
    shell: '{{ forgejo___user.shell }}'
    home: '{{ forgejo___user.home }}'
    create_home: '{{ forgejo___user.create_home }}'
    password: '{{ forgejo___user.password }}'
    password_lock: '{{ forgejo___user.password_lock }}'
    update_password: '{{ forgejo___user.update_password }}'
    expires: '{{ forgejo___user.expires }}'
    system: '{{ forgejo___user.system }}'

# Pre-existing users may have a different UID/GID/Home.
- name: '{{ "Prep | account | enumerate " ~ forgejo__srv._user }}'
  ansible.builtin.user:
    name: '{{ forgejo__srv._user }}'
  check_mode: true
  changed_when: false
  register: forgejo__cfg_query

- name: 'Prep | fact | parse service UID/GID'
  ansible.builtin.set_fact:
    forgejo__cfg: "{{ forgejo__cfg | r_pufky.data.v3(

        _uid=forgejo__cfg_query.uid,
        _gid=forgejo__cfg_query.group,
        _home=forgejo__cfg_query.home,
        _ssh=forgejo__cfg_query.home ~ '/.ssh',
      ) }}"

# Update working directory location if custom user setting.
- name: 'Prep | fact | resolve app.ini'
  when: forgejo__cfg._file | length > 0
  ansible.builtin.set_fact:
    forgejo__srv: "{{ forgejo__srv | r_pufky.data.v3(

        _tmpl_cfg=lookup('ansible.builtin.template', forgejo__cfg._file),
      ) }}"

- name: 'Prep | fact | parse WORK_PATH'
  ansible.builtin.set_fact:
    forgejo__cfg: "{{ forgejo__cfg | r_pufky.data.v3(

        _work_path=(
          forgejo__srv._tmpl_cfg |
          regex_search(\"^WORK_PATH\\s*=\\s*(.+)$\", '\\1', multiline=True) |
          default(forgejo___app._var_d) | first | trim
        ),
      ) }}"
