---
- name: 'Directories | converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Directories | converge | apply r_pufky.srv.forgejo'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.forgejo'
