---
###############################################################################
# Directories
###############################################################################
# Relative paths are resolved and created correctly.
#
# Tests:
# * Relative managed directory paths are resolved properly (absolute path with
#   no trailing slash).
# * Managed directory paths are created correctly.

dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        repo_testing_enable: true
        repo_testing_versions:
          - comment: 'forgejo'
            version: 'v11.0.3'
            asset: '{{
                lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
                "/molecule/cache/forgejo-11.0.3-linux-amd64"
              }}'
            checksum: '{{
                lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
                "/molecule/cache/forgejo-11.0.3-linux-amd64.sha256"
              }}'
            signature: '{{
                lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
                "/molecule/cache/forgejo-11.0.3-linux-amd64.asc"
              }}'
        forgejo_srv_container_enable: true
        forgejo_srv_harden_enable: true
        forgejo_cfg_security_internal_token: 'test'
        forgejo_cfg_server_lfs_jwt_secret: 'test'
        forgejo_cfg_security_secret_key: 'test'
        forgejo_cfg_repository_root: 'gitea-repositories'
        forgejo_cfg_repository_upload_temp_path: 'data/tmp/uploads'
        forgejo_cfg_repository_local_local_copy_path: 'tmp/local-repo'
        forgejo_cfg_server_pprof_data_path: 'data/tmp/pprof'
        forgejo_cfg_database_path: 'forgejo.db'
        forgejo_cfg_indexer_issue_indexer_path: 'indexers/issues.bleve'
        forgejo_cfg_indexer_repo_indexer_path: 'indexers/repos.bleve'
        forgejo_cfg_queue_datadir: 'queues/common'
        forgejo_cfg_server_acme_directory: 'https'
        forgejo_cfg_session_provider_config: 'data/sessions'
        forgejo_cfg_attachment_path: 'attachments'
        forgejo_cfg_log_root_path: 'log'
        forgejo_cfg_git_home_path: 'home'
        forgejo_cfg_packages_chunked_upload_path: 'tmp/package-upload'
        forgejo_cfg_packages_path: 'packages'
platforms:
  - name: 'forgejo-debian-12-directories'
    image: 'ghcr.io/hifis-net/debian-systemd:12'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    # - 'dependency'
    # - 'cleanup'
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    # - 'idempotence'  # Files created, extracted, created, deleted.
    # - 'side_effect'
    - 'verify'
    # - 'cleanup'
    - 'destroy'
