---
# yamllint disable rule:line-length
- name: 'Directories | prepare'
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: 'Directories | prepare | generate cache location'
      ansible.builtin.set_fact:
        _test_cache: '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/molecule/cache'

    - name: 'Directories | prepare | create cache'
      ansible.builtin.file:
        path: '{{ _test_cache }}'
        mode: '0755'
        state: 'directory'

    - name: 'Directories | prepare | check forgejo v10.0.3'
      ansible.builtin.stat:
        path: '{{ _test_cache }}/forgejo-10.0.3-linux-amd64'
      register: _test_prepare

    - name: 'Directories | prepare | cache forgejo v10.0.3'
      when: not _test_prepare.stat.exists
      ansible.builtin.get_url:
        url: 'https://codeberg.org/forgejo/forgejo/releases/download/v10.0.3/forgejo-10.0.3-linux-amd64'
        dest: '{{ _test_cache }}/forgejo-10.0.3-linux-amd64'
        mode: '0750'
      retries: 5
      delay: 5

    - name: 'Directories | prepare | check forgejo v10.0.3 checksum'
      ansible.builtin.stat:
        path: '{{ _test_cache }}/forgejo-10.0.3-linux-amd64.sha256'
      register: _test_prepare

    - name: 'Directories | prepare | cache forgejo v10.0.3 checksum'
      when: not _test_prepare.stat.exists
      ansible.builtin.get_url:
        url: 'https://codeberg.org/forgejo/forgejo/releases/download/v10.0.3/forgejo-10.0.3-linux-amd64.sha256'
        dest: '{{ _test_cache }}/forgejo-10.0.3-linux-amd64.sha256'
        mode: '0640'
      retries: 5
      delay: 5

    - name: 'Directories | prepare | check forgejo v10.0.3 signature'
      ansible.builtin.stat:
        path: '{{ _test_cache }}/forgejo-10.0.3-linux-amd64.asc'
      register: _test_prepare

    - name: 'Directories | prepare | cache forgejo v10.0.3 signature'
      when: not _test_prepare.stat.exists
      ansible.builtin.get_url:
        url: 'https://codeberg.org/forgejo/forgejo/releases/download/v10.0.3/forgejo-10.0.3-linux-amd64.asc'
        dest: '{{ _test_cache }}/forgejo-10.0.3-linux-amd64.asc'
        mode: '0640'
      retries: 5
      delay: 5
