---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | app.ini'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'lineinfile.yml'
      vars:
        test_name: 'Verify | app.ini | {{ item }}'
        test_file: '/etc/forgejo/app.ini'
        test_line: '{{ item }}'
        test_state: 'present'
        test_diff: true
      loop:
        - 'ROOT = /srv/git/forgejo/gitea-repositories'
        - 'TEMP_PATH = /srv/git/forgejo/data/tmp/uploads'
        - 'LOCAL_COPY_PATH = /srv/git/forgejo/data/tmp/local-repo'
        - 'APP_DATA_PATH = /srv/git/forgejo/data'
        - 'PPROF_DATA_PATH = /srv/git/forgejo/data/tmp/pprof'
        - 'PATH = /srv/git/forgejo/data/forgejo.db'
        - 'ISSUE_INDEXER_PATH = /srv/git/forgejo/indexers/issues.bleve'
        - 'REPO_INDEXER_PATH = /srv/git/forgejo/indexers/repos.bleve'
        - 'DATADIR = /srv/git/forgejo/data/queues/common'
        - 'ACME_DIRECTORY = /etc/forgejo/https'
        - 'PROVIDER_CONFIG = /srv/git/forgejo/data/sessions'
        - 'PATH = /srv/git/forgejo/data/attachments'
        - 'ROOT_PATH = /srv/git/forgejo/log'
        - 'HOME_PATH = /srv/git/forgejo/data/home'
        - 'CHUNKED_UPLOAD_PATH = /srv/git/forgejo/data/tmp/package-upload'
        - 'PATH = /srv/git/forgejo/data/packages'

    - name: 'Verify | permissions'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Verify | permissions | {{ item }}'
        test_file: '{{ item }}'
        test_owner: '305'
        test_group: '305'
        test_mode: '0755'
        test_state: 'directory'
        test_diff: true
      loop:
        - '/srv/git/forgejo/gitea-repositories'
        - '/srv/git/forgejo/data/tmp/uploads'
        - '/srv/git/forgejo/data/tmp/local-repo'
        - '/srv/git/forgejo/data'
        - '/srv/git/forgejo/data/tmp/pprof'
        - '/srv/git/forgejo/data'  # forgejo.db.
        - '/srv/git/forgejo/indexers/issues.bleve'
        - '/srv/git/forgejo/indexers/repos.bleve'
        - '/srv/git/forgejo/data/queues/common'
        - '/etc/forgejo/https'
        - '/srv/git/forgejo/data/sessions'
        - '/srv/git/forgejo/data/attachments'
        - '/srv/git/forgejo/log'
        - '/srv/git/forgejo/data/home'
        - '/srv/git/forgejo/data/tmp/package-upload'
        - '/srv/git/forgejo/data/packages'
