---
###############################################################################
# Backup
###############################################################################
# Version upgrades trigger automatic install backup before upgrade if enabled.
#
# Tests:
# * Upgrading forgejo trigger backup of existing data.

dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        repo_testing_enable: true
        repo_testing_versions:
          - comment: 'forgejo'
            version: 'v10.0.3'
            asset: '{{
                lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
                "/molecule/cache/forgejo-10.0.3-linux-amd64"
              }}'
            checksum: '{{
                lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
                "/molecule/cache/forgejo-10.0.3-linux-amd64.sha256"
              }}'
            signature: '{{
                lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
                "/molecule/cache/forgejo-10.0.3-linux-amd64.asc"
              }}'
          - comment: 'forgejo'
            version: 'v10.0.4'
            asset: '{{
                lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
                "/molecule/cache/forgejo-10.0.4-linux-amd64"
              }}'
            checksum: '{{
                lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
                "/molecule/cache/forgejo-10.0.4-linux-amd64.sha256"
              }}'
            signature: '{{
                lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
                "/molecule/cache/forgejo-10.0.4-linux-amd64.asc"
              }}'
        forgejo_container_enable: true
        forgejo_service_harden_enable: true
        forgejo_config_security_install_lock: true
        forgejo_local_users:
          - username: 'admin_test'
            password: 'admin'
            email: 'admin@example.com'
            admin: true
          - username: 'user_test'
            password: 'test'
            email: 'user@example.com'
          - username: 'user_test'
            state: 'absent'
platforms:
  - name: 'forgejo-debian-12-backup'
    image: 'ghcr.io/hifis-net/debian-systemd:12'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    # - 'dependency'
    # - 'cleanup'
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    # - 'idempotence'  # Files created, extracted, created, deleted.
    # - 'side_effect'
    - 'verify'
    # - 'cleanup'
    - 'destroy'
