---
###############################################################################
# Backup
###############################################################################
# Version upgrades trigger automatic install backup before upgrade if enabled.
#
# Tests:
# * Upgrading forgejo trigger backup of existing data.

dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        repo_testing_enable: true
        repo_testing_versions:
          - comment: 'forgejo'
            version: 'v11.0.3'
            asset: '{{
                lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
                "/molecule/cache/forgejo-11.0.3-linux-amd64"
              }}'
            checksum: '{{
                lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
                "/molecule/cache/forgejo-11.0.3-linux-amd64.sha256"
              }}'
            signature: '{{
                lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
                "/molecule/cache/forgejo-11.0.3-linux-amd64.asc"
              }}'
          - comment: 'forgejo'
            version: 'v11.0.4'
            asset: '{{
                lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
                "/molecule/cache/forgejo-11.0.4-linux-amd64"
              }}'
            checksum: '{{
                lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
                "/molecule/cache/forgejo-11.0.4-linux-amd64.sha256"
              }}'
            signature: '{{
                lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
                "/molecule/cache/forgejo-11.0.4-linux-amd64.asc"
              }}'
        forgejo_srv_container_enable: true
        forgejo_cfg_security_install_lock: true
        forgejo_srv_backup_repository_skip: true
        forgejo_srv_backup_lfs_data_skip: true
        forgejo_srv_harden_enable: false
        # TODO(role): Need to evaluate container/vm/bare metal -- systemd
        #     hardening works for all other tests except this one where the
        #     service is installed, then upgraded. Let Trixie settled and see
        #     if issues arise when it is in the wild longer than a week.
        #     Currently, disabling these protects resolves the issue:
        #     * PrivateDevices
        #     * ProtectClock
        #     * ProtectKernelTunables
        #     * ProtectKernelModules
        #     * ProtectKernelLogs
        #     * RestrictNamespaces
        #     * LockPersonality
        #     * MemoryDenyWriteExecute
        #     * RestrictRealtime
        #     * RestrictSUIDGUID
platforms:
  - name: 'forgejo-debian-13-backup'
    image: 'ghcr.io/hifis-net/debian-systemd:13'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    # - 'dependency'
    # - 'cleanup'
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    # - 'idempotence'  # Files created, extracted, created, deleted.
    # - 'side_effect'
    - 'verify'
    # - 'cleanup'
    - 'destroy'
