---
- name: 'Backup | prepare'
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: 'Backup | prepare | generate cache location'
      ansible.builtin.set_fact:
        _test_cache:
          '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/molecule/cache'

    - name: 'Backup | prepare | cache'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'create_cache.yml'
      vars:
        test_name: 'Backup | prepare | cache'
        test_cache: '{{ _test_cache }}/ssh'

    - name: 'Backup | prepare | check forgejo v10.0.3'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'cache_url.yml'
      vars:
        test_name: 'Backup | prepare | check forgejo v10.0.3'
        test_dest: 'forgejo-10.0.3-linux-amd64'
        test_url: '{{
            "https://codeberg.org/forgejo/forgejo/releases/download/" ~
            "v10.0.3/" ~
            "forgejo-10.0.3-linux-amd64"
          }}'
        test_mode: '0750'

    - name: 'Backup | prepare | check forgejo v10.0.3 checksum'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'cache_url.yml'
      vars:
        test_name:
          'Backup | prepare | check forgejo v10.0.3 checksum'
        test_dest: 'forgejo-10.0.3-linux-amd64.sha256'
        test_url: '{{
            "https://codeberg.org/forgejo/forgejo/releases/download/" ~
            "v10.0.3/" ~
            "forgejo-10.0.3-linux-amd64.sha256"
          }}'
        test_mode: '0640'

    - name: 'Backup | prepare | check forgejo v10.0.3 signature'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'cache_url.yml'
      vars:
        test_name:
          'Backup | prepare | check forgejo v10.0.3 signature'
        test_dest: 'forgejo-10.0.3-linux-amd64.asc'
        test_url: '{{
            "https://codeberg.org/forgejo/forgejo/releases/download/" ~
            "v10.0.3/" ~
            "forgejo-10.0.3-linux-amd64.asc"
          }}'
        test_mode: '0640'

    - name: 'Backup | prepare | cache forgejo v10.0.4'
      ansible.builtin.command:
        argv:
          - 'cp'
          - '{{ _test_cache }}/forgejo-10.0.3-linux-amd64'
          - '{{ _test_cache }}/forgejo-10.0.4-linux-amd64'
        creates: '{{ _test_cache }}/forgejo-10.0.4-linux-amd64'

    - name: 'Backup | prepare | cache forgejo v10.0.4 checksum'
      ansible.builtin.command:
        argv:
          - 'cp'
          - '{{ _test_cache }}/forgejo-10.0.3-linux-amd64.sha256'
          - '{{ _test_cache }}/forgejo-10.0.4-linux-amd64.sha256'
        creates: '{{ _test_cache }}/forgejo-10.0.4-linux-amd64.sha256'
      register: _test_prepare

    - name: 'Backup | prepare | update forgejo v10.0.4 checksum'
      when: _test_prepare.changed  # noqa no-handler
      ansible.builtin.command:
        argv:
          - 'sed'
          - '-i'
          - 's/10.0.3/10.0.4/g'
          - '{{ _test_cache }}/forgejo-10.0.4-linux-amd64.sha256'
      changed_when: true

    - name: 'Backup | prepare | cache forgejo v10.0.4 signature'
      ansible.builtin.command:
        argv:
          - 'cp'
          - '{{ _test_cache }}/forgejo-10.0.3-linux-amd64.asc'
          - '{{ _test_cache }}/forgejo-10.0.4-linux-amd64.asc'
        creates: '{{ _test_cache }}/forgejo-10.0.4-linux-amd64.asc'

    - name: 'Backup | prepare | cache PKCS8 RSA private key'
      ansible.builtin.command:
        argv:
          - 'openssl'
          - 'genrsa'
          - '-out'
          - '{{ _test_cache }}/oauth2.rsa.pem'
          - '4096'
        creates: '{{ _test_cache }}/oauth2.rsa.pem'

    - name: 'Backup | prepare | cache PKCS8 RSA private key'
      ansible.builtin.command:
        argv:
          - 'openssl'
          - 'pkcs8'
          - '-topk8'
          - '-inform'
          - 'PEM'
          - '-nocrypt'
          - '-in'
          - '{{ _test_cache }}/oauth2.rsa.pem'
          - '-out'
          - '{{ _test_cache }}/oauth2.pkcs8.pem'
        creates: '{{ _test_cache }}/oauth2.pkcs8.pem'

    - name: 'Backup | prepare | cache forgejo_config_security_internal_token'
      ansible.builtin.shell: >-
        {{ _test_cache }}/forgejo-10.0.3-linux-amd64
        generate secret INTERNAL_TOKEN
        > {{ _test_cache }}/security_internal_token
      args:
        creates: '{{ _test_cache }}/security_internal_token'

    - name: 'Backup | prepare | cache forgejo_config_server_lfs_jwt_secret'
      ansible.builtin.shell: >-
        {{ _test_cache }}/forgejo-10.0.3-linux-amd64
        generate secret JWT_SECRET
        > {{ _test_cache }}/lfs_jwt_secret
      args:
        creates: '{{ _test_cache }}/lfs_jwt_secret'

    - name: 'Backup | prepare | cache forgejo_config_security_secret_key'
      ansible.builtin.shell: >-
        {{ _test_cache }}/forgejo-10.0.3-linux-amd64
        generate secret SECRET_KEY
        > {{ _test_cache }}/secret_key
      args:
        creates: '{{ _test_cache }}/secret_key'

    - name: 'Backup | prepare | cache forgejo_config_server_cert_file'
      ansible.builtin.command:
        argv:
          - '{{ _test_cache }}/forgejo-10.0.3-linux-amd64'
          - 'cert'
          - '-ca=true'
          - '-duration=8760h0m0s'
          - '-host=test.example.com'
        chdir: '{{ _test_cache }}'
        creates: '{{ _test_cache }}/cert.pem'

    - name: 'Backup | prepare | generate testing host key'
      ansible.builtin.command:
        argv:
          - 'ssh-keygen'
          - '-t'
          - 'rsa'
          - '-b'
          - '4096'
          - '-f'
          - '{{ _test_cache }}/ssh/host_key'
          - '-C'
          - ''
          - '-N'
          - ''
        creates: '{{ _test_cache }}/ssh/host_key'  # and host_key.pub
