---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | enumerate backups'
      ansible.builtin.find:
        paths: '/srv/forgejo/data/backup'
        follow: true
        recurse: false
        file_type: 'file'
      register: _forgejo_test_backups

    - name: 'Verify | assert backups'
      ansible.builtin.assert:
        quiet: true
        that: _forgejo_test_backups.files | length > 0
        fail_msg: |
          ╭───────────────────────────────────────────────────────────────────╮
          │                                                                   │
          │          No backup was made in /srv/forgejo/data/backup.          │
          │                                                                   │
          ╰───────────────────────────────────────────────────────────────────╯
