---
###############################################################################
# Config
###############################################################################
# All configuration sections are broken down into individual files in section/.
# Empty options are not rendered. All config values follow the built-in
# Forgejo config rules below:
#
# * Always use full paths or YAML replacement for full paths. Most path options
#   Support %(APP_INI_VAR)s replacement strings but will NOT be interpreted
#   during role application (e.g. creating any necessary directories). Relative
#   references are kept for context only.
# * App.ini uses CAP_UNDER; these translate to
#   forgejo_cfg_{SECTION}_{HEADER}_{VAR}.
#
# Config References:
#          AppPath: APP_PATH - Absolute path of running binary. Automatically
#                   detected.
#      AppWorkPath: APP_WORK_PATH - Working directory (where a majority of data
#                   should be placed). forgejo_cfg_work_path.
#      AppDataPath: APP_DATA_PATH - Data directory. forgejo_cfg_data_path.
#       CustomPath: CUSTOM_PATH - Base directory for custom templates and other
#                   options. forgejo_cfg_custom_path.
#       CustomConf: Configuration file. CustomPath/app.ini.
#   StaticRootPath: AppWorkPath.
#
# Value Formats:
#   TIME (time): A duration string is a possibly signed sequence of decimal
#         numbers, each with optional fraction and a unit suffix, such as
#         '300ms', '-1.5h' or '2h45m'.
#       Values:
#         ns: nanoseconds.
#         us: microseconds.
#         µs: microseconds.
#         ms: milliseconds.
#          s: seconds.
#          m: minutes.
#          h: hours.
#   SIZE (size): All standard sizes are supported (MB, MiB, etc).
#       Values:
#              -1: No limit.
#               #: Bytes.
#         #{SIZE}: Size specifier (MB, GiB, etc).
#
# Reference:
# * https://pkg.go.dev/time#Duration
# * https://github.com/dustin/go-humanize
# * https://forgejo.org/docs/latest/admin/config-cheat-sheet/

# Absolute path to ETC base directory.
#
# Sets CustomPath. Used for app.ini and certificates.
#
# Default: '/etc/forgejo'.
forgejo_cfg_custom_path: '/etc/forgejo'

###############################################################################
# General Options [no section]
###############################################################################

# Application name. Default: 'Forgejo: Beyond coding. We Forge.'.
forgejo_cfg_app_name: 'Forgejo: Beyond coding. We Forge.'

# Application slogan. Default: ''.
forgejo_cfg_app_slogan: ''

# Application name format.
#
# Only used if forgejo_cfg_app_slogan is set.
#
# Special Case:
#   {APP_NAME}: forgejo_cfg_app_name replacement.
#   {APP_SLOGAN}: forgejo_cfg_app_slogan replacement.
#
# Default: '{APP_NAME}: {APP_SLOGAN}'.
forgejo_cfg_app_display_name_format: '{APP_NAME}: {APP_SLOGAN}'

# User application runs as.
#
# Values:
#   '': Autodetect (default).
#
# Default: '' (autodetect).
forgejo_cfg_run_user: '{{ forgejo_srv_user }}'

# Application run mode.
#
# Affects performance and debugging.
#
# Values:
#      *: Production use.
#    dev: Development and debugging.
#   prod: Production use (default).
#
# Default: 'prod'.
forgejo_cfg_run_mode: 'prod'

# Absolute path to Forgejo working directory.
#
# Sets AppWorkPath. Used for static templates and general process caching.
#
# Default: '/opt/forgejo'.
forgejo_cfg_work_path: '/opt/forgejo'

# Absolute path to Forgejo data directory.
#
# Sets AppDataPath. User data stored here.
#
# Default: '/srv/git/data'.
forgejo_cfg_data_path: '/srv/git/data'
