---
- name: 'Converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Converge | import role variables'
      ansible.builtin.include_vars:
        file: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/vars/main.yml"
          }}'

    - name: 'Converge | fact | set cache location'
      ansible.builtin.set_fact:
        forgejo__test_cache: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/molecule/cache"
          }}'

    - name: 'Converge | cache | load cached tokens'
      ansible.builtin.set_fact:
        internal_token: "{{
            lookup('ansible.builtin.file',
                   forgejo__test_cache ~ '/internal_token')
          }}"
        jwt_secret: "{{
            lookup('ansible.builtin.file', forgejo__test_cache ~ '/jwt_secret')
          }}"
        lfs_jwt_secret: "{{
            lookup('ansible.builtin.file',
                   forgejo__test_cache ~ '/lfs_jwt_secret')
          }}"

    # Always reset app.ini to remove pre-install detection on new test runs.
    - name: '{{ "Converge | cache | reset " ~ forgejo___app._app_ini }}'
      ansible.builtin.file:
        path: '{{ forgejo___app._app_ini }}'
        state: 'absent'

    - name: 'Converge | role | r_pufky.srv.forgejo (new install)'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.forgejo'

    - name: 'Converge | role | r_pufky.srv.forgejo (forgejo_flg_config)'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.forgejo'
      vars:
        forgejo_flg_config: true
        forgejo_cfg_file: '{{
            lookup("env", "MOLECULE_SCENARIO_DIRECTORY") ~ "/files/app.ini"
          }}'
        forgejo_cfg_d: '{{
            lookup("env", "MOLECULE_SCENARIO_DIRECTORY") ~ "/files/dir"
          }}'
