---
###############################################################################
# Default
###############################################################################
# Default role configuration applies correctly with hardening enabled.
#
# Tests:
# * service is active and running (default).
# * Default configuration is syntactically correct.
# * Deployed configuration directory is set correctly.
# * Hardened drop-in works.
# * Backup pre-operation works for forgejo_flg_config
# * admin_test user is created and can login.
# * user_test user is removed.

dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        molecule_flg_inject: true
        forgejo_flg_backup: true
        forgejo_srv_harden: true
        forgejo_cfg_users:
          - username: 'admin_test'
            password: 'adminadmin'
            email: 'admin@example.com'
            admin: true
          - username: 'user_test'
            password: 'testtest'
            email: 'user@example.com'
          - username: 'user_test'
            state: 'absent'
        forgejo_cfg_backup_opts:
          - '--database sqlite3'
          - '--skip-repository'
          - '--skip-log'
          - '--skip-custom-dir'
          - '--skip-lfs-data'
          - '--skip-attachment-data'
          - '--skip-package-data'
          - '--skip-index'
          - '--skip-repo-archives'
          - '--type tar.xz'
platforms:
  - name: 'forgejo-default'
    image: 'ghcr.io/hifis-net/debian-systemd:13'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    capabilities:
      - 'SYS_ADMIN'  # Required for testing systemd hardening.
    command: '/lib/systemd/systemd'
    pre_build_image: true
    published_ports:
      - '3000:3000/tcp'
verifier:
  name: 'ansible'
scenario:
  test_sequence:
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    - 'verify'
    - 'destroy'
