---
- name: 'Prepare'
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: 'Prepare | import role variables'
      ansible.builtin.include_vars:
        file: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/vars/main.yml"
          }}'

    - name: 'Prepare | cache'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'create_cache.yml'
      vars:
        test_name: 'Prepare cache'

    - name: 'Prepare | fact | set cache location'
      ansible.builtin.set_fact:
        forgejo__test_cache: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/molecule/cache"
          }}'
        forgejo__test_bin: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/molecule/cache/" ~
            forgejo___app._package_bin
          }}'

    - name: '{{  "Prepare | cache | Forgejo " ~ forgejo___app._version }}'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'cache_url.yml'
      vars:
        test_name:
          '{{  "Prepare | cache | Forgejo " ~ item }}'
        test_dest: '{{ item }}'
        test_url: '{{ forgejo___app._url_base ~ item }}'
        test_mode: '0640'
      loop:
        - '{{ forgejo___app._package }}'
        - '{{ forgejo___app._package_sig }}'
        - '{{ forgejo___app._package_sum }}'

    - name: 'Prepare | cache | extract binary for local token generation'
      ansible.builtin.shell: '{{
          "xz -d " ~ forgejo___app._package ~ " && " ~
          "chmod 0755 " ~ forgejo___app._package_bin
        }}'
      args:
        executable: '/bin/bash'
        chdir: '{{ forgejo__test_cache }}'
        creates: '{{ forgejo__test_bin }}'
      changed_when: true

    - name: 'Prepare | cache | INTERNAL_TOKEN'
      ansible.builtin.shell: '{{
          forgejo__test_bin ~
          " generate secret INTERNAL_TOKEN > internal_token"
        }}'
      args:
        executable: '/bin/bash'
        chdir: '{{ forgejo__test_cache }}'
        creates: '{{ forgejo__test_cache ~ "/internal_token" }}'
      changed_when: true

    - name: 'Prepare | cache | JWT_SECRET'
      ansible.builtin.shell: '{{
          forgejo__test_bin ~ " generate secret JWT_SECRET > jwt_secret"
        }}'
      args:
        executable: '/bin/bash'
        chdir: '{{ forgejo__test_cache }}'
        creates: '{{ forgejo__test_cache ~ "/jwt_secret" }}'
      changed_when: true

    - name: 'Prepare | cache | LFS_JWT_SECRET'
      ansible.builtin.shell: '{{
          forgejo__test_bin ~
          " generate secret LFS_JWT_SECRET > lfs_jwt_secret"
        }}'
      args:
        executable: '/bin/bash'
        chdir: '{{ forgejo__test_cache }}'
        creates: '{{ forgejo__test_cache ~ "/lfs_jwt_secret" }}'
      changed_when: true

- name: 'Prepare'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Prepare | import role variables'
      ansible.builtin.include_vars:
        file: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/vars/main.yml"
          }}'

    - name: 'Prepare | inject | cached packages'
      when: (molecule_flg_inject | default(false))
      ansible.builtin.copy:
        src: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/molecule/cache/" ~
            item
          }}'
        dest: '{{ "/tmp/" ~ item }}'
        owner: 'root'
        group: 'root'
        mode: '0644'
      loop:
        - '{{ forgejo___app._package }}'
        - '{{ forgejo___app._package_sig }}'
        - '{{ forgejo___app._package_sum }}'

- name: 'Prepare'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name:
        'Prepare | inject | required testing packages'
      ansible.builtin.apt:
        name: 'curl'  # Required for testing login.
        state: 'present'
