---
###############################################################################
# Verify
###############################################################################

- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | import role variables'
      ansible.builtin.include_vars:
        file: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/vars/main.yml"
          }}'

    # Test forgejo_cfg_d. Service will not start if forgejo_cfg_file is bad.
    - name: '{{ "Verify | test | " ~ forgejo___app._work_d ~ "/README.md" }}'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'copy.yml'
      vars:
        test_name:
          '{{ "Verify | test | " ~ forgejo___app._work_d ~ "/README.md" }}'
        test_src: '{{
            lookup("env", "MOLECULE_SCENARIO_DIRECTORY") ~
            "/files/dir/README.md"
          }}'
        test_file: '{{ forgejo___app._work_d ~ "/README.md" }}'
        test_owner: 'git'
        test_group: 'git'
        test_mode: '0640'
        test_diff: true

    - name: '{{
          "Verify | filesystem | query " ~ forgejo___app._data_d ~ "/backup"
        }}'
      ansible.builtin.find:
        path: '{{ forgejo___app._data_d ~ "/backup" }}'
        patterns: '*.xz'
        file_type: 'file'
        recurse: false
      register: forgejo__backup

    - name: 'Verify | assert | pre-operation backup triggered'
      ansible.builtin.assert:
        quiet: true
        that: 'forgejo__backup.matched >= 1'
        fail_msg: '✘ Backup should be triggered on forgejo_flg_config run.'

    - name: 'Verify | assert | admin user created'
      ansible.builtin.command:
        argv:
          - '{{ forgejo___app._bin }}'
          - '--config'
          - '{{ forgejo___app._app_ini }}'
          - 'admin'
          - 'user'
          - 'list'
      changed_when: false
      failed_when: '"admin@example.com" not in forgejo__test_user_list.stdout'
      become: true
      become_user: 'git'
      register: forgejo__test_user_list

    - name: 'Verify | assert | standard user deleted'
      ansible.builtin.command:
        argv:
          - '{{ forgejo___app._bin }}'
          - '--config'
          - '{{ forgejo___app._app_ini }}'
          - 'admin'
          - 'user'
          - 'list'
      changed_when: false
      failed_when: '"user@example.com" in forgejo__test_user_list.stdout'
      become: true
      become_user: 'git'
      register: forgejo__test_user_list

    - name: 'Verify | query | admin_test login success'
      ansible.builtin.command:
        argv:
          - 'curl'
          - '-X'
          - 'POST'
          - '-F'
          - 'user_name=admin_test'
          - '-F'
          - 'password=adminadmin'
          - 'http://127.0.0.1:3000/user/login'
      changed_when: false
      register: forgejo__test_login

    - name: 'Verify | assert local user login success'
      ansible.builtin.assert:
        quiet: true
        that:
          - forgejo__test_login.stdout is not
            search("Username or password is incorrect.")
        fail_msg: '✘ admin_test@127.0.0.1 should successfully login.'
