---
- name: 'Converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Converge | generate cache location'
      ansible.builtin.set_fact:
        _test_cache:
          '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/molecule/cache'

    - name: 'Converge | load cached secrets'
      ansible.builtin.set_fact:
        _test_oauth2_rsa_pem:
          '{{ lookup("file", _test_cache ~ "/oauth2.rsa.pem") }}'
        _test_oauth2_pkcs8_pem:
          '{{ lookup("file", _test_cache ~ "/oauth2.pkcs8.pem") }}'
        _test_security_internal_token:
          '{{ lookup("file", _test_cache ~ "/security_internal_token") }}'
        _test_lfs_jwt_secret:
          '{{ lookup("file", _test_cache ~ "/lfs_jwt_secret") }}'
        _test_secret_key: '{{ lookup("file", _test_cache ~ "/secret_key") }}'
        _test_cert_pem: '{{ lookup("file", _test_cache ~ "/cert.pem") }}'
        _test_cert_key: '{{ lookup("file", _test_cache ~ "/key.pem") }}'

    - name: 'Converge | render expected app.ini'
      ansible.builtin.template:
        src: 'templates/app.ini.j2'
        dest: '/tmp/app.ini'
        owner: '305'
        group: '305'
        mode: '0640'

    - name: 'Converge | apply r_pufky.srv.forgejo'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.forgejo'
      vars:
        forgejo_cfg_security_internal_token:
          '{{ _test_security_internal_token }}'
        forgejo_cfg_server_lfs_jwt_secret: '{{ _test_lfs_jwt_secret }}'
        forgejo_cfg_security_secret_key: '{{ _test_secret_key }}'
        forgejo_cfg_oauth2_jwt_secret: '{{ _test_lfs_jwt_secret }}'
