---
- name: 'Converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Converge | generate cache location'
      ansible.builtin.set_fact:
        _test_cache:
          '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/molecule/cache'

    - name: 'Converge | load cached secrets'
      ansible.builtin.set_fact:
        _test_lfs_jwt_secret:
          '{{ lookup("file", _test_cache ~ "/lfs_jwt_secret") }}'
        _test_secret_key: '{{ lookup("file", _test_cache ~ "/secret_key") }}'

    # Indirectly test default security key warning.
    - name: >
        Converge |
        assert data locations are not in install paths
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'assertions.yml'
      vars:
        test_name: >
          Converge |
          assert data locations are not in install paths
        test_role: 'r_pufky.srv.forgejo'
        test_fail_message:
          'forgejo_cfg_work_path="/tmp/test" did not trigger assertion.'
        forgejo_cfg_security_secret_key: '!#@FDEWREWR&*('
        forgejo_cfg_server_lfs_jwt_secret: '{{ _test_lfs_jwt_secret }}'
        forgejo_cfg_data_path: '/tmp/test'
        forgejo_cfg_work_path: '/tmp/test'
        forgejo_cfg_custom_path: '/tmp/test2'
        forgejo_role_repo_extract_symlink: '/tmp/test2'

    - name: >
        Converge |
        assert data locations are not in install paths
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'assertions.yml'
      vars:
        test_name: >
          Converge |
          assert data locations are not in install paths
        test_role: 'r_pufky.srv.forgejo'
        test_fail_message:
          'forgejo_cfg_custom_path="/tmp/test" did not trigger assertion.'
        forgejo_cfg_security_secret_key: '{{ _test_secret_key }}'
        forgejo_cfg_server_lfs_jwt_secret: '{{ _test_lfs_jwt_secret }}'
        forgejo_cfg_data_path: '/tmp/test'
        forgejo_cfg_work_path: '/tmp/test2'
        forgejo_cfg_custom_path: '/tmp/test'
        forgejo_role_repo_extract_symlink: '/tmp/test2'

    - name: >
        Converge |
        assert data locations are not in install paths
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'assertions.yml'
      vars:
        test_name: >
          Converge |
          assert data locations are not in install paths
        test_role: 'r_pufky.srv.forgejo'
        test_fail_message: >
          forgejo_role_repo_extract_symlink="/tmp/test"
          did not trigger assertion.
        forgejo_cfg_security_secret_key: '{{ _test_secret_key }}'
        forgejo_cfg_server_lfs_jwt_secret: '{{ _test_lfs_jwt_secret }}'
        forgejo_cfg_data_path: '/tmp/test'
        forgejo_cfg_work_path: '/tmp/test2'
        forgejo_cfg_custom_path: '/tmp/test2'
        forgejo_role_repo_extract_symlink: '/tmp/test'

    - name: 'Converge | user manual confirmation'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'assertions.yml'
      vars:
        test_name: 'Converge | user manual confirmation'
        test_role: 'r_pufky.srv.forgejo'
        test_fail_message: >
          forgejo_cfg_service_register_email_confirm=true
          did not trigger assertion.
        forgejo_cfg_service_register_manual_confirm: true
        forgejo_cfg_service_register_email_confirm: true

    - name: 'Converge | registration only using forgejo'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'assertions.yml'
      vars:
        test_name:
          'Converge | registration only using forgejo'
        test_role: 'r_pufky.srv.forgejo'
        test_fail_message: >
          forgejo_cfg_service_register_email_confirm=true
          did not trigger assertion.
        forgejo_cfg_service_allow_only_internal_registration: true
        forgejo_cfg_service_register_email_confirm: true

    - name: >
        Converge |
        registration using third-party services
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'assertions.yml'
      vars:
        test_name: >
          Converge |
          registration using third-party services
        test_role: 'r_pufky.srv.forgejo'
        test_fail_message: >
          forgejo_cfg_service_register_email_confirm=true
          did not trigger assertion.
        forgejo_cfg_service_allow_only_external_registration: true
        forgejo_cfg_service_register_email_confirm: true

    - name: 'Converge | Google recaptcha (secret)'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'assertions.yml'
      vars:
        test_name: 'Converge | Google recaptcha (secret)'
        test_role: 'r_pufky.srv.forgejo'
        test_fail_message: >
          forgejo_cfg_service_recaptcha_secret="" did not trigger assertion.
        forgejo_cfg_service_recaptcha_secret: ''
        forgejo_cfg_service_recaptcha_sitekey: 'test'

    - name: 'Converge | Google recaptcha (sitekey)'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'assertions.yml'
      vars:
        test_name:
          'Converge | Google recaptcha (sitekey)'
        test_role: 'r_pufky.srv.forgejo'
        test_fail_message: >
          forgejo_cfg_service_recaptcha_sitekey=""
          did not trigger assertion.
        forgejo_cfg_service_recaptcha_secret: 'test'
        forgejo_cfg_service_recaptcha_sitekey: ''

    - name: 'Converge | hCaptcha recaptcha (secret)'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'assertions.yml'
      vars:
        test_name:
          'Converge | hCaptcha recaptcha (secret)'
        test_role: 'r_pufky.srv.forgejo'
        test_fail_message: >
          forgejo_cfg_service_hcaptcha_secret=""
          did not trigger assertion.
        forgejo_cfg_service_hcaptcha_secret: ''
        forgejo_cfg_service_hcaptcha_sitekey: 'test'

    - name: 'Converge | hCaptcha recaptcha (sitekey)'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'assertions.yml'
      vars:
        test_name:
          'Converge | hCaptcha recaptcha (sitekey)'
        test_role: 'r_pufky.srv.forgejo'
        test_fail_message: >
          forgejo_cfg_service_hcaptcha_sitekey="" did not trigger assertion.
        forgejo_cfg_service_hcaptcha_secret: 'test'
        forgejo_cfg_service_hcaptcha_sitekey: ''

    - name: 'Converge | mCaptcha recaptcha (URL)'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'assertions.yml'
      vars:
        test_name: 'Converge | mCaptcha recaptcha (URL)'
        test_role: 'r_pufky.srv.forgejo'
        test_fail_message:
          'forgejo_cfg_service_mcaptcha_url="" did not trigger assertion.'
        forgejo_cfg_service_mcaptcha_url: ''
        forgejo_cfg_service_mcaptcha_secret: 'test'
        forgejo_cfg_service_mcaptcha_sitekey: 'test'

    - name: 'Converge | mCaptcha recaptcha (secret)'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'assertions.yml'
      vars:
        test_name:
          'Converge | mCaptcha recaptcha (secret)'
        test_role: 'r_pufky.srv.forgejo'
        test_fail_message: >
          forgejo_cfg_service_mcaptcha_secret="" did not trigger assertion.
        forgejo_cfg_service_mcaptcha_url: 'test'
        forgejo_cfg_service_mcaptcha_secret: ''
        forgejo_cfg_service_mcaptcha_sitekey: 'test'

    - name: 'Converge | mCaptcha recaptcha (sitekey)'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'assertions.yml'
      vars:
        test_name:
          'Converge | mCaptcha recaptcha (sitekey)'
        test_role: 'r_pufky.srv.forgejo'
        test_fail_message: >
          forgejo_cfg_service_mcaptcha_sitekey="" did not trigger assertion.
        forgejo_cfg_service_mcaptcha_url: 'test'
        forgejo_cfg_service_mcaptcha_secret: 'test'
        forgejo_cfg_service_mcaptcha_sitekey: ''

    - name: >
        Converge |
        Cloudflare Turnstile recaptcha (secret)
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'assertions.yml'
      vars:
        test_name: >
          Converge |
          Cloudflare Turnstile recaptcha (secret)
        test_role: 'r_pufky.srv.forgejo'
        test_fail_message: >
          forgejo_cfg_service_cf_turnstile_secret=""
          did not trigger assertion.
        forgejo_cfg_service_cf_turnstile_secret: ''
        forgejo_cfg_service_cf_turnstile_sitekey: 'test'

    - name: >
        Converge |
        Cloudflare Turnstile recaptcha (sitekey)
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'assertions.yml'
      vars:
        test_name: >
          Converge |
          Cloudflare Turnstile recaptcha (sitekey)
        test_role: 'r_pufky.srv.forgejo'
        test_fail_message: >
          forgejo_cfg_service_cf_turnstile_sitekey=""
          did not trigger assertion.
        forgejo_cfg_service_cf_turnstile_secret: 'test'
        forgejo_cfg_service_cf_turnstile_sitekey: ''

    - name:
        'Converge | forgejo_cfg_security_secret_key'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'assertions.yml'
      vars:
        test_name:
          'Converge | forgejo_cfg_security_secret_key'
        test_role: 'r_pufky.srv.forgejo'
        test_fail_message:
          'forgejo_cfg_security_secret_key="" did not trigger assertion.'
        forgejo_cfg_security_secret_key: ''

    - name: 'Converge | ACME server (TOS)'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'assertions.yml'
      vars:
        test_name: 'Converge | ACME server (TOS)'
        test_role: 'r_pufky.srv.forgejo'
        test_fail_message:
          'forgejo_cfg_server_acme_accepttos="" did not trigger assertion.'
        forgejo_cfg_security_secret_key: '{{ _test_secret_key }}'
        forgejo_cfg_server_enable_acme: true
        forgejo_cfg_server_acme_accepttos: false
        forgejo_cfg_server_acme_email: 'test'
        forgejo_cfg_server_acme_directory: 'test'

    - name: 'Converge | ACME server (email)'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'assertions.yml'
      vars:
        test_name: 'Converge | ACME server (email)'
        test_role: 'r_pufky.srv.forgejo'
        test_fail_message:
          'forgejo_cfg_server_acme_email="" did not trigger assertion.'
        forgejo_cfg_security_secret_key: '{{ _test_secret_key }}'
        forgejo_cfg_server_enable_acme: true
        forgejo_cfg_server_acme_accepttos: true
        forgejo_cfg_server_acme_email: ''
        forgejo_cfg_server_acme_directory: 'test'

    - name: 'Converge | ACME server (directory)'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'assertions.yml'
      vars:
        test_name: 'Converge | ACME server (directory)'
        test_role: 'r_pufky.srv.forgejo'
        test_fail_message:
          'forgejo_cfg_server_acme_directory="" did not trigger assertion.'
        forgejo_cfg_security_secret_key: '{{ _test_secret_key }}'
        forgejo_cfg_server_enable_acme: true
        forgejo_cfg_server_acme_accepttos: true
        forgejo_cfg_server_acme_email: 'test'
        forgejo_cfg_server_acme_directory: ''

    - name: 'Converge | LFS JWT secret'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'assertions.yml'
      vars:
        test_name: 'Converge | LFS JWT secret'
        test_role: 'r_pufky.srv.forgejo'
        forgejo_cfg_security_secret_key: '{{ _test_secret_key }}'
        test_fail_message:
          'forgejo_cfg_server_lfs_jwt_secret="" did not trigger assertion.'
        forgejo_cfg_server_lfs_jwt_secret: ''

    - name: 'Converge | required Camo settings (URL)'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'assertions.yml'
      vars:
        test_name:
          'Converge | required Camo settings (URL)'
        test_role: 'r_pufky.srv.forgejo'
        test_fail_message:
          'forgejo_cfg_server_lfs_jwt_secret="" did not trigger assertion.'
        forgejo_cfg_security_secret_key: '{{ _test_secret_key }}'
        forgejo_cfg_server_lfs_jwt_secret: '{{ _test_lfs_jwt_secret }}'
        forgejo_cfg_camo_enabled: true
        forgejo_cfg_camo_server_url: 'test'
        forgejo_cfg_camo_hmac_key: ''

    - name: 'Converge | required Camo settings (key)'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'assertions.yml'
      vars:
        test_name:
          'Converge | required Camo settings (key)'
        test_role: 'r_pufky.srv.forgejo'
        test_fail_message:
          'forgejo_cfg_server_lfs_jwt_secret="" did not trigger assertion.'
        forgejo_cfg_security_secret_key: '{{ _test_secret_key }}'
        forgejo_cfg_server_lfs_jwt_secret: '{{ _test_lfs_jwt_secret }}'
        forgejo_cfg_camo_enabled: true
        forgejo_cfg_camo_server_url: ''
        forgejo_cfg_camo_hmac_key: 'test'

    - name:
        'Converge | required database settings (host)'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'assertions.yml'
      vars:
        test_name:
          'Converge | required Camo settings (host)'
        test_role: 'r_pufky.srv.forgejo'
        test_fail_message:
          'forgejo_cfg_database_host="" did not trigger assertion.'
        forgejo_cfg_security_secret_key: '{{ _test_secret_key }}'
        forgejo_cfg_server_lfs_jwt_secret: '{{ _test_lfs_jwt_secret }}'
        forgejo_cfg_database_db_type: 'postgres'
        forgejo_cfg_database_host: ''
        forgejo_cfg_database_name: 'test'
        forgejo_cfg_database_user: 'test'
        forgejo_cfg_database_passwd: 'test'

    - name:
        'Converge | required database settings (name)'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'assertions.yml'
      vars:
        test_name:
          'Converge | required database settings (name)'
        test_role: 'r_pufky.srv.forgejo'
        test_fail_message:
          'forgejo_cfg_database_name="" did not trigger assertion.'
        forgejo_cfg_security_secret_key: '{{ _test_secret_key }}'
        forgejo_cfg_server_lfs_jwt_secret: '{{ _test_lfs_jwt_secret }}'
        forgejo_cfg_database_db_type: 'postgres'
        forgejo_cfg_database_host: 'test'
        forgejo_cfg_database_name: ''
        forgejo_cfg_database_user: 'test'
        forgejo_cfg_database_passwd: 'test'

    - name:
        'Converge | required database settings (user)'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'assertions.yml'
      vars:
        test_name:
          'Converge | required database settings (user)'
        test_role: 'r_pufky.srv.forgejo'
        test_fail_message:
          'forgejo_cfg_database_user="" did not trigger assertion.'
        forgejo_cfg_security_secret_key: '{{ _test_secret_key }}'
        forgejo_cfg_server_lfs_jwt_secret: '{{ _test_lfs_jwt_secret }}'
        forgejo_cfg_database_db_type: 'postgres'
        forgejo_cfg_database_host: 'test'
        forgejo_cfg_database_name: 'test'
        forgejo_cfg_database_user: ''
        forgejo_cfg_database_passwd: 'test'

    - name:
        'Converge | required database settings (passwd)'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'assertions.yml'
      vars:
        test_name: >
          Converge | required database settings (passwd)
        test_role: 'r_pufky.srv.forgejo'
        test_fail_message:
          'forgejo_cfg_database_passwd="" did not trigger assertion.'
        forgejo_cfg_security_secret_key: '{{ _test_secret_key }}'
        forgejo_cfg_server_lfs_jwt_secret: '{{ _test_lfs_jwt_secret }}'
        forgejo_cfg_database_db_type: 'postgres'
        forgejo_cfg_database_host: 'test'
        forgejo_cfg_database_name: 'test'
        forgejo_cfg_database_user: 'test'
        forgejo_cfg_database_passwd: ''

    - name: 'Converge | Oauth2 JWT secret'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'assertions.yml'
      vars:
        test_name: 'Converge | Oauth2 JWT secret'
        test_role: 'r_pufky.srv.forgejo'
        test_fail_message:
          'forgejo_cfg_oauth2_jwt_secret="" did not trigger assertion.'
        forgejo_cfg_security_secret_key: '{{ _test_secret_key }}'
        forgejo_cfg_server_lfs_jwt_secret: '{{ _test_lfs_jwt_secret }}'
        forgejo_cfg_oauth2_jwt_signing_algorithm: 'HS256'
        forgejo_cfg_oauth2_jwt_secret: ''

    - name: 'Converge | log request headers'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'assertions.yml'
      vars:
        test_name: 'Converge | log request headers'
        test_role: 'r_pufky.srv.forgejo'
        test_fail_message:
          'forgejo_cfg_log_logger_access_mode="" did not trigger assertion.'
        forgejo_cfg_security_secret_key: '{{ _test_secret_key }}'
        forgejo_cfg_server_lfs_jwt_secret: '{{ _test_lfs_jwt_secret }}'
        forgejo_cfg_log_request_id_headers:
          - 'X-Request-ID'
          - 'X-Trace-ID'
          - 'X-Req-ID'
        forgejo_cfg_log_logger_access_mode: ''

    - name: 'Converge | mailer client certificates (cert)'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'assertions.yml'
      vars:
        test_name:
          'Converge | mailer client certificates (cert)'
        test_role: 'r_pufky.srv.forgejo'
        test_fail_message:
          'forgejo_cfg_mailer_client_key_file="" did not trigger assertion.'
        forgejo_cfg_security_secret_key: '{{ _test_secret_key }}'
        forgejo_cfg_server_lfs_jwt_secret: '{{ _test_lfs_jwt_secret }}'
        forgejo_cfg_mailer_use_client_cert: true
        forgejo_cfg_mailer_client_cert_file: ''
        forgejo_cfg_mailer_client_key_file: '/tmp/test'

    - name: 'Converge | mailer client certificates (key)'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'assertions.yml'
      vars:
        test_name:
          'Converge | mailer client certificates (key)'
        test_role: 'r_pufky.srv.forgejo'
        test_fail_message:
          'forgejo_cfg_mailer_client_key_file="" did not trigger assertion.'
        forgejo_cfg_security_secret_key: '{{ _test_secret_key }}'
        forgejo_cfg_server_lfs_jwt_secret: '{{ _test_lfs_jwt_secret }}'
        forgejo_cfg_mailer_use_client_cert: true
        forgejo_cfg_mailer_client_cert_file: '/tmp/test'
        forgejo_cfg_mailer_client_key_file: ''
