---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | jwt/private.pem'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Verify | jwt/private.pem'
        test_src: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/cache/oauth2.pkcs8.pem"
          }}'
        test_file: '/srv/forgejo/data/jwt/private.pem'
        test_owner: 'git'
        test_group: 'git'
        test_mode: '0400'
        test_diff: true

    - name: 'Verify | mailer/cert.pem'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Verify | mailer/cert.pem'
        test_src: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/cache/cert.pem"
          }}'
        test_file: '/srv/forgejo/mailer/cert.pem'
        test_owner: 'git'
        test_group: 'git'
        test_mode: '0400'
        test_diff: true

    - name: 'Verify | mailer/cert.key'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Verify | mailer/cert.key'
        test_src: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/cache/key.pem"
          }}'
        test_file: '/srv/forgejo/mailer/cert.key'
        test_owner: 'git'
        test_group: 'git'
        test_mode: '0400'
        test_diff: true

    - name: 'Verify | enumerate server host keys'
      ansible.builtin.find:
        paths: '/srv/forgejo/data/ssh'
        excludes: ['*.pub']
        follow: true
        recurse: true
        file_type: 'file'
      register: _forgejo_test_server_host_keys

    - name: 'Verify | assert server host keys'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Verify | assert server host keys'
        test_src: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/cache/ssh/" ~
            item.path | basename
          }}'
        test_file: '{{ item.path }}'
        test_owner: 'git'
        test_group: 'git'
        test_mode: '0400'
        test_diff: true
      loop: '{{ _forgejo_test_server_host_keys.files }}'
      loop_control:
        label: '{{ item.path }}'

    - name: 'Verify | ca_trust_chain_root.pem'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Verify | ca_trust_chain_root.pem'
        test_src: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/cache/cert.pem"
          }}'
        test_file: '/srv/forgejo/https/ca_trust_chain_root.pem'
        test_owner: 'git'
        test_group: 'git'
        test_mode: '0400'
        test_diff: true

    - name: 'Verify | user trust keys'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Verify | user trust keys'
        test_src: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/cache/cert.pem"
          }}'
        test_file: '/srv/forgejo/.ssh/ca_trust_chain_root.pem'
        test_owner: 'git'
        test_group: 'git'
        test_mode: '0400'
        test_diff: true

    - name: 'Verify | server certificates'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Verify | server certificates'
        test_src: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/cache/" ~
            item.src
          }}'
        test_file: '{{ item.file }}'
        test_owner: '305'
        test_group: '305'
        test_mode: '0400'
        test_diff: true
      loop:
        - {src: 'cert.pem', file: '/srv/forgejo/https/cert.pem'}
        - {src: 'key.pem', file: '/srv/forgejo/https/cert.key'}
      loop_control:
        label: '{{ item.file }}'
